language: python
python:
  - '3.7'
services:
  - docker
# run through the test suite and usage examples in a docker container as well
before_install:
  - mkdir -p $TRAVIS_BUILD_DIR/docker_out
  - docker build -t snpseq_metadata .
  - docker run -v $TRAVIS_BUILD_DIR:/mnt/metadata snpseq_metadata pytest /mnt/metadata/tests/
  - docker run -v $TRAVIS_BUILD_DIR:/mnt/metadata snpseq_metadata bash /mnt/metadata/tests/validate_test_data.sh /mnt/metadata /mnt/metadata/docker_out
install:
  - pip install -r requirements_dev.txt -e .
script:
- pytest tests/
- mkdir -p python_out
- bash tests/validate_test_data.sh "$(pwd)" "python_out"
notifications:
  email: false
