language: python
python:
  - '3.7'
env:
  - SCHEMAURL=https://raw.githubusercontent.com/enasequence/schema/master/src/main/resources/uk/ac/ebi/ena/sra/schema
services:
  - docker
install:
  - pip install -r requirements_dev.txt -e .
  # download from GitHub in travis since FTP is not working
  - snpseq_metadata/scripts/generate_python_models.sh xsdata $SCHEMAURL
before_script:
  - docker build --build-arg schema_url=$SCHEMAURL -t snpseq_metadata .
script:
# run pytest suite and integration test script
- pytest tests/
- mkdir python_out
- bash tests/validate_test_data.sh "$(pwd)" "python_out"
# run through the test suite and integration test script in the docker container as well
- mkdir docker_out
- docker run -v $TRAVIS_BUILD_DIR:/mnt/metadata snpseq_metadata pytest tests/
- docker run -v $TRAVIS_BUILD_DIR:/mnt/metadata snpseq_metadata bash tests/validate_test_data.sh /mnt/metadata /mnt/metadata/docker_out
notifications:
  email: false
